permalink: pretty
markdown: kramdown

title: Password Policy List
author: Cody Hoover
description:
    List of sites and their password policies including length, characterset, and other restrictions
url: http://www.perfectpass.org/
repo: https://github.com/hoovercj/perfectpass
img: img/logo.png
siteurl: "http://www.perfectpass.org"

exclude:
    - CNAME
    - CONTRIBUTING.md
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - Rakefile
    - verify.rb
