permalink: pretty
markdown: kramdown

title: Password Policy List
author: Cody Hoover
description:
    List of sites and their password policies including length, characterset, and other restrictions
url: http://www.codyhoover.com/passwordpolicies/
repo: https://github.com/hoovercj/passwordpolicies
img: img/logo.png

exclude:
    - CNAME
    - CONTRIBUTING.md
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - Rakefile
    - verify.rb
