websites:
pending:
    - name: CAcert
      url: https://www.cacert.org/
      twitter: CAcert_News
      img: cacert.png
      
    - name: DigiCert
      url: http://www.digicert.com/
      twitter: digicert
      img: digicert.png
                  
    - name: Dome9 Security
      url: http://www.dome9.com/
      img: dome9.png
                        
    - name: GeoTrust
      url: http://www.geotrust.com/
      img: geotrust.png
            
    - name: Norton
      url: http://us.norton.com
      img: norton.png
                              
    - name: OpenDNS
      url: http://www.opendns.com/
      img: opendns.png
      twitter: OpenDNS
                            
    - name: SSLTrust
      url: http://ssltrust.com.au/
      img: ssltrust.png
                  
    - name: ThreatMetrix
      url: https://www.threatmetrix.com/
      img: threatmetrix.png
      twitter: ThreatMetrix

    - name: ThreatSim
      url: http://login.threatsim.com
      img: threatsim.png
                  
    - name: Tinfoil Security
      url: https://www.tinfoilsecurity.com
      img: tinfoil.png
                  
    - name: Webroot
      url: http://www.webroot.com
      img: webroot.png
      twitter: Webroot
      